INSERT INTO "job_position" (
    "id", "event_id", "position_category_id", "salary", "currency", "capacity", "name", "description", "is_opened_for_registration", "instructions_html")
VALUES
    (1, 1, 6, 150, 'CZK', 2, 'Stánek s hotdogy', 'Prodej hotdogů a dalších rychlých jídel návštěvníkům', True, 'Buď připraven obsluhovat rychle a s úsměvem. Udržuj pult čistý, dodržuj hygienické standardy a buď připraven na rychlou přípravu a prodej hotdogů.'),
    (2, 1, 7, 180, 'CZK', 3, 'Technická podpora', 'Kompletní technické zajištění festivalu', True, 'Zajisti kompletní technické vybavení včetně ozvučení, osvětlení a dalších technických zařízení. Buď připraven rychle reagovat na případné technické problémy.'),
    (3, 1, 2, 160, 'CZK', 2, 'Koordinace vstupu', 'Komplexní organizace vstupů a registrace návštěvníků', False, 'Organizuj registraci a kontrolu vstupenek. Buď přehledný, komunikativní a dodržuj stanovený postup při vpouštění návštěvníků.'),
    (4, 2, 2, 140, 'CZK', 1, 'Koordinace parkoviště', 'Precizní organizace parkování', True, 'Usměrňuj parkování, udržuj pořádek a plynulost provozu. Buď vstřícný a jasně naviguj řidiče na volná místa.'),
    (5, 2, 5, 200, 'CZK', 5, 'Zdravotnický tým', 'Komplexní zdravotnické zabezpečení akce', False, 'Buď připraven poskytovat první pomoc, mít pohotovostní lékárničku a rychle reagovat na zdravotní komplikace návštěvníků.'),
    (6, 2, 4, 130, 'CZK', 2, 'Úklidový tým', 'Komplexní úklid a údržba areálu', True, 'Pravidelně uklízej prostory, udržuj čistotu a pořádek. Buď flexibilní a připravený na okamžitý úklid.'),
    (7, 3, 1, 170, 'CZK', 1, 'Ochranka', 'Bezpečnostní dohled nad festivalem', True, 'Zajišťuj bezpečnost, monitoruj prostor a předcházej konfliktním situacím. Jednej profesionálně a klidně.'),
    (8, 3, 1, 160, 'CZK', 3, 'Kontrola vstupenek', 'Komplexní organizace vstupů', True, 'Pečlivě kontroluj vstupenky, ověřuj jejich platnost a usměrňuj tok návštěvníků.'),
    (9, 3, 3, 130, 'CZK', 2, 'Výpomoc v šatně', 'Organizace šatny a péče o věci návštěvníků', False, 'Organizuj ukládání a vydávání osobních věcí, buď pozorný a pečlivý při manipulaci s věcmi návštěvníků.'),
    (10, 4, 7, 180, 'CZK', 5, 'Technická podpora', 'Specializovaná technická podpora pódia', True, 'Specializovaná technická podpora pro pódiové vybavení. Buď připraven na okamžité řešení technických záležitostí.'),
    (11, 4, 2, 150, 'CZK', 3, 'Koordinace parkoviště', 'Komplexní řízení parkování', True, 'Organizuj registraci a kontrolu vstupenek. Buď přehledný, komunikativní a dodržuj stanovený postup při vpouštění návštěvníků.'),
    (12, 4, 4, 140, 'CZK', 2, 'Úklidový tým', 'Údržba čistoty a pořádku', False, 'Specializovaná technická podpora pro pódiové vybavení. Buď připraven na okamžité řešení technických záležitostí.'),
    (13, 5, 5, 200, 'CZK', 1, 'Zdravotnický tým', 'Specializovaná zdravotnická pomoc', True, 'Poskytuj specializovanou zdravotnickou pomoc, buď připraven řešit různé zdravotní situace.'),
    (14, 5, 1, 160, 'CZK', 3, 'Kontrola vstupenek', 'Komplexní organizace vstupů', True, 'Pečlivě kontroluj vstupenky, ověřuj jejich platnost a usměrňuj tok návštěvníků.'),
    (15, 5, 6, 150, 'CZK', 2, 'Občerstvení', 'Příprava a distribuce jídla', False, 'Připravuj a distribuuj jídlo, udržuj čistotu stánku a buď rychlý a vstřícný.'),
    (16, 6, 1, 180, 'CZK', 1, 'Bezpečnostní tým', 'Specializovaný bezpečnostní dohled', True, 'Zajišťuj komplexní bezpečnostní dohled, buď připraven rychle a profesionálně řešit potenciální bezpečnostní rizika.'),
    (17, 6, 3, 130, 'CZK', 3, 'Šatnový tým', 'Komplexní správa šatny', True, 'Komplexně spravuj šatnu, buď organizovaný a pečlivý při přijímání a vydávání svršků.'),
    (18, 6, 4, 140, 'CZK', 2, 'Úklidové práce', 'Komplexní údržba areálu', False, 'Pravidelně uklízej prostory, udržuj čistotu a pořádek. Buď flexibilní a připravený na okamžitý úklid.'),
    (19, 7, 7, 170, 'CZK', 2, 'Technická podpora', 'Specializovaná technická asistence', True, 'Specializovaná technická asistence. Buď připraven na okamžité řešení technických záležitostí.'),
    (20, 7, 5, 190, 'CZK', 3, 'Zdravotnický tým', 'Komplexní zdravotnické zabezpečení', True, 'Komplexní zdravotnické zabezpečení. Buď připraven poskytovat specializovanou zdravotnickou pomoc.'),
    (21, 7, 2, 150, 'CZK', 2, 'Organizace vstupu', 'Koordinace vstupů a registrace', False, 'Koordinuj vstupy a registrace. Buď přehledný, komunikativní a dodržuj stanovený postup.'),
    (22, 8, 2, 135, 'CZK', 1, 'Koordinace dopravy', 'Specializovaná dopravní organizace', True, 'Specializovaná dopravní organizace. Usměrňuj přesuny a zajišťuj plynulost pohybu.'),
    (23, 8, 6, 145, 'CZK', 3, 'Občerstvení', 'Komplexní zajištění stravování', True, 'Komplexně zajišťuj stravování, buď rychlý, vstřícný a udržuj čistotu stánku.'),
    (24, 8, 4, 125, 'CZK', 2, 'Úklidový tým', 'Údržba pořádku a čistoty', False, 'Udržuj pořádek a čistotu. Buď flexibilní a připravený na okamžitý úklid.'),
    (25, 9, 1, 130, 'CZK', 3, 'Kontrola vstupu', 'Specializovaná vstupní kontrola', True, 'Prováděj specializovanou vstupní kontrolu, buď důsledný a pozorný při ověřování vstupenek.'),
    (26, 9, 7, 160, 'CZK', 3, 'Technická podpora', 'Komplexní technické zabezpečení', True, 'Komplexní technické zabezpečení. Buď připraven rychle reagovat na technické problémy.'),
    (27, 9, 2, 140, 'CZK', 5, 'Koordinace parkoviště', 'Organizace parkování', False, 'Organizuj parkování, udržuj pořádek a usměrňuj dopravu na parkovišti.'),
    (28, 10, 4, 120, 'CZK', 1, 'Úklidový tým', 'Specializovaný úklid', True, 'Prováděj specializovaný úklid, buď důsledný a flexibilní při udržování čistoty.'),
    (29, 10, 5, 190, 'CZK', 3, 'Zdravotnická péče', 'Komplexní zdravotnické služby', True, 'Poskytuj komplexní zdravotnické služby, buď připraven rychle reagovat na zdravotní komplikace.'),
    (30, 10, 1, 170, 'CZK', 2, 'Bezpečnostní dohled', 'Organizace bezpečnosti', False, 'Organizuj bezpečnost, monitoruj prostor a předcházej potenciálním konfliktním situacím.'),
    (31, 11, 3, 130, 'CZK', 1, 'Šatnový personál', 'Specializovaná správa šatny', True, 'Specializovaná správa šatny. Buď organizovaný a pečlivý při manipulaci s osobními věcmi.'),
    (32, 11, 2, 145, 'CZK', 3, 'Koordinace parkoviště', 'Komplexní řízení dopravy', True, 'Komplexně řiď dopravu, usměrňuj parkování a zajišťuj plynulost provozu.'),
    (33, 11, 3, 150, 'CZK', 2, 'Vstupenky', 'Organizace vstupů', False, 'Organizuj vstupy, kontroluj vstupenky a usměrňuj tok návštěvníků.'),
    (34, 12, 7, 160, 'CZK', 3, 'Technická podpora', 'Specializovaná technická asistence', True, 'Specializovaná technická asistence. Buď připraven rychle řešit technické záležitosti.'),
    (35, 12, 5, 190, 'CZK', 3, 'Zdravotnický tým', 'Komplexní zdravotnické zabezpečení', True, 'Komplexní zdravotnické zabezpečení. Poskytuj profesionální zdravotnickou pomoc.'),
    (36, 12, 4, 140, 'CZK', 2, 'Úklidové práce', 'Údržba pořádku', False, 'Udržuj pořádek, prováděj pravidelný úklid a buď flexibilní při řešení úklidových potřeb.');

SELECT setval(pg_get_serial_sequence('"job_position"', 'id'), MAX("id")) FROM "job_position";