DELETE FROM "position_category" WHERE "name" = 'Finance';
DELETE FROM "position_category" WHERE "name" = 'Security';
DELETE FROM "position_category" WHERE "name" = 'Maintenance';
DELETE FROM "position_category" WHERE "name" = 'Guest Services';
DELETE FROM "position_category" WHERE "name" = 'Coordination';
DELETE FROM "position_category" WHERE "name" = 'Food Service';
DELETE FROM "position_category" WHERE "name" = 'Technical Support';
DELETE FROM "position_category" WHERE "name" = 'Transportation';
DELETE FROM "position_category" WHERE "name" = 'Media';
