name: Trigger auto deployment for homework-2-web-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/homework-2-web-app-AutoDeployTrigger-052fac22-ce0b-41c0-a634-795167d7711c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HOMEWORK2WEBAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HOMEWORK2WEBAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HOMEWORK2WEBAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: homework2cr.azurecr.io
          registryUsername: ${{ secrets.HOMEWORK2WEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HOMEWORK2WEBAPP_REGISTRY_PASSWORD }}
          containerAppName: homework-2-web-app
          resourceGroup: Homework_2
          imageToBuild: homework2cr.azurecr.io/homework-2-web-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


